routes/web.php
<?php

use App\Http\Controllers\admin\AdminController;
use App\Http\Controllers\admin\InstagramController;
use App\Http\Controllers\admin\ModerationController;
use App\Http\Controllers\admin\PostController;
use App\Http\Controllers\admin\SettingController;
use App\Http\Controllers\front\CommentController;
use App\Http\Controllers\front\ContactUsFormController;
use App\Http\Controllers\front\FrontController;
use App\Http\Controllers\sitemap\SitemapController;
use Illuminate\Support\Facades\Route;
require __DIR__.'/auth.php';

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/







/*
|--------------------------------------------------------------------------
| SITEMAP Routes
|--------------------------------------------------------------------------
|
|
|
*/
Route::get('/sitemap', [SitemapController::class, 'index'])->name('sitemap.index');









/*
|--------------------------------------------------------------------------
| ADMIN Routes
|--------------------------------------------------------------------------
|
|
|
*/
Route::prefix('/admin')->middleware('auth')->namespace('admin')->group(function () {

    // HOME ADMIN
    // HOME ADMIN
    Route::get('/', [AdminController::class, 'index'])->name('homeadmin');

    // CRUD POSTS
    // CRUD POSTS
    Route::get('/allposts', [PostController::class, 'allposts'])->name('allposts'); // allposts datatable admin route
    Route::get('/post/create', [PostController::class, 'create'])->name('create'); // create new post route
    Route::post('/post', [PostController::class, 'store'])->name('upload.post'); // upload post route
    Route::get('/post/{post}/edit', [PostController::class, 'edit']); // edit post route
    Route::get('/post/{post}', [PostController::class, 'show']); // see one post route
    Route::put('/post/{post}', [PostController::class, 'update']); // update post route
    Route::delete('/post/{post}', [PostController::class, 'destroy']);

    // UPLOAD IMAGE
    // UPLOAD IMAGE
    Route::post('/saveimage', [PostController::class, 'uploadImages']);

    // SETTINGS ROUTES
    // SETTINGS ROUTES
    Route::get('/settings', [SettingController::class, 'allsettings'])->name('allsettings'); // settings admin route
    // CATEGORIES
    Route::post('/store-cat', [SettingController::class, 'store_cat'])->name('upload.category'); // create new category
    Route::delete('/delete-cat/{category}', [SettingController::class, 'destroy_cat']);
    // TAGS
    Route::post('/store-tag', [SettingController::class, 'store_tag'])->name('upload.tag'); // create new tag
    Route::post('/store_tag_in_post_create', [SettingController::class, 'store_tag_in_post_create'])->name('create.store_tag_in_post_create'); // create new tag
    Route::delete('/delete-tag/{tag}', [SettingController::class, 'destroy_tag']);

    // INSTAGRAM ROUTES
    // INSTAGRAM ROUTES
    Route::get('/manage-insta', [InstagramController::class, 'show_insta'])->name('show_insta');
    Route::post('/store-insta', [InstagramController::class, 'store_insta'])->name('upload.insta');
    Route::delete('/delete-insta/{instagram}', [InstagramController::class, 'destroy_insta']);

    //MODERATION ROUTES
    //MODERATION ROUTES
    // COMMENTS
    Route::get('/moderation-comments', [ModerationController::class, 'comments'])->name('comments');
    Route::delete('/delete-comment/{comment}', [ModerationController::class, 'destroy']);
    Route::post('/verif-comment/{comment}', [ModerationController::class, 'verified']);
    // USERS
    Route::get('/moderation-allusers', [ModerationController::class, 'allusers'])->name('allusers');

});




/*
|--------------------------------------------------------------------------
|       FRONT ROUTES
|--------------------------------------------------------------------------
|
|
|
*/
    // HOME
Route::get('/', [FrontController::class, 'homeposts'])->name('home');

    // MENTIONS LEGALES
Route::get('/mentions-legales', [FrontController::class, 'mentionslegales'])->name('mentionslegales');

    // COMMENTS FOR ONE POST
Route::post('/comments/store', [CommentController::class, 'store'])->name('comment.store');

    // CONTACT
Route::get('/contact', [ContactUsFormController::class, 'createForm'])->name('contact');
Route::post('/contact', [ContactUsFormController::class, 'ContactUsForm'])->name('contact.store');

/*
|------------------
|       SLUG
|------------------
*/
    // SORTING POST BY CATEGORY
Route::get('/{category:category_slug}', [FrontController::class, 'postByCat']);

// GO TO ONE POST
Route::get('/{category:slug}/{post:slug}', [FrontController::class, 'show'])->name('post');

app/Models/Post.php
<?php

namespace App\Models;

use App\Core\FileSaving\FilesSaving;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Post extends Model
{
    use HasFactory;
    use FilesSaving;

    protected $fillable = ['title', 'category_id', 'main_img', 'body', 'chapo', 'meta_desc', 'alt_main_img', 'location', 'slug'];

    public function category(): HasOne
    {
        return $this->hasOne(Category::class, 'id', 'category_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'posts_tags', 'post_id','tag_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, 'post_id', 'id')
            ->where('parent_id', '=', null)

            ->where(function ($query){
                return  $query->where('verified_at', '!=', null)
                    ->orWhere('email', '=', 'faustine.clerc1@gmail.com');
            });
    }
}

app/Http/Controllers/admin/PostController.php
<?php

namespace App\Http\Controllers\admin;

use App\Core\FileSaving\FilesSavingClass;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Comment;
use App\Models\PostTag;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\Post;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PostController extends Controller
{
    public function allposts()
    {
        $posts = Post::where('is_published', '=', true)->with('category')->withCount('comments')->get();
        $postsDraft = Post::where('is_published', '=', false)->get();
        return view('admin.posts.allposts', compact('posts', 'postsDraft'));
    }

    public function create()
    {
        $tags = Tag::all();
        $categories = Category::all();

        return view('admin.posts.create', compact('categories', 'tags'));
    }

    public function store(Request $request)
    {
        /*$request->validate([
            'title' => 'required',
            'tag' => 'required',
            'category' => 'required',
            'main_img' => 'required',
            'body' => 'required',
        ]);*/

        $post = new Post();
        $post->title = $request->title;
        $post->category_id = $request->category;
        $post->main_img = $post->saveImageToDisk($request->file('file'), 'posts', $post->title);
        $post->body = $request->body;
        $post->chapo = $request->chapo;
        $post->meta_desc = $request->meta_desc;
        $post->alt_main_img = $request->alt_main_img;
        $post->location = $request->location;
        $post->slug = Str::slug($request->title, "-");

        if ($request->has('save'))
        {
            $post->is_published = false;
        }
        else if ($request->has('publish'))
        {
            $post->is_published = true;
        }

        $post->save();
        /*foreach ($request->tagsTet as $tag) {

            $postTag            = new PostTag();
            $postTag->post_id   = $post->id;
            $postTag->tag_id    = $tag;

            $postTag->save();
        }*/
        $post->tags()->sync($request->tagsTet);

        return redirect('/admin/allposts')->with('success', 'Post created successfully!');
    }

    public function show(Post $post)
    {
        $post = $post->load([
            'category',
            'tags',
            'comments.childs',
        ]);
        $totalComments = Comment::where('post_id', '=', $post->id)->count();

        return view('admin/posts/show', compact('post', 'totalComments'));
    }

    public function edit(Post $post)
    {
        $tags = Tag::all();
        $categories = Category::all();

        return view('admin.posts.edit', compact('post', 'categories', 'tags'));
    }

    public function update(Request $request, Post $post)
    {
        /*$request->validate([
            'title' => 'required',
            'category_id' => 'required',
            //'main_img' => 'required',
            'body' => 'required',
            'chapo' => 'required',
            'meta_desc' => 'required',
            'alt_main_img' => 'required',
            'location' => 'required',
        ]);*/
        $post->title = $request->title;
        $post->category_id = $request->category;
        $post->body = $request->body;
        $post->chapo = $request->chapo;
        $post->meta_desc = $request->meta_desc;
        $post->alt_main_img = $request->alt_main_img;
        $post->location = $request->location;
        $post->slug = Str::slug($request->title, "-");

        if ($request->has('save'))
        {
            $post->is_published = false;
        }
        else if ($request->has('publish'))
        {
            $post->is_published = true;
        }

        $post->save();

        $post->main_img = $post->saveImageToDisk($request->file('file'), 'posts', $post->title);

        $post->tags()->sync($request->tagsTet);
        /* foreach ($request->tagsTet as $tag) {


             $postTag            = new PostTag();
             $postTag->post_id   = $post->id;
             $postTag->tag_id    = $tag;

             $postTag->save();
         }*/
        return redirect('/admin/allposts')->with('success', 'L\'article a bien été mis à jour !!!');
    }

    public function destroy(Post $post)
    {
        $post->delete();

        return redirect('/admin/allposts')->with('success', 'Post deleted successfully!');
    }

    //upload img (in summernote and input form)
    public function uploadImages(Request $request)
    {
        $fileSaving = new FilesSavingClass();
        return $fileSaving->saveImageToDisk($request->file('file'), 'posts', md5(rand(100, 200)));
    }
    /*    public function uploadImages(Request $request)
    {
        $file = $request->file('file');
        if ($request->title !== null) {
            $name = $request->title . '-' . Carbon::now()->format('d-m-Y');
        } else {
            $name = md5(rand(100, 200));
        }

        $filename = Str::slug($name) . '.' . $file->getClientOriginalExtension();
        $pathTemp = '/uploads/' . Carbon::now()->format('Y/m');

        Storage::putFileAs('public' . $pathTemp, $file, $filename);

        return $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . '/storage/' . $pathTemp . '/' . $filename;
    }
*/
}

resources/views/admin/posts/allposts.blade.php
@extends('admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 mt-4">
                <a href="{{ route('create') }}" class="btn btn-green mb-2" style="width: 50%;">Create Post</a>
            </div>
        </div>
        <div class="card">
            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
                <br/>
            @endif
            <div class="card-header">
                <h2>Les articles publiés</h2>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table class="table table-bordered sortDataTable">

                    <thead>
                    <tr>
                        <th>Img</th>
                        <th>Title</th>
                        <th>Tag</th>
                        <th>Categorie</th>
                        <th>Contenu</th>
                        <th>Commentaires</th>
                        <th>Cree le</th>
                        <th>Modifier le</th>
                        <th class="text-center">Voir</th>
                        <th class="text-center">Modif</th>
                        <th class="text-center">Suppr</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td style="width: 150px;">
                                <img src="{!! $post->main_img !!}" alt="{{ $post->alt_main_img }}" style="width: 100%;">
                            </td>
                            <td style="width: 150px;">{{ $post->title }}</td>
                            <td>
                                @foreach($post->tags as $tag)
                                    <span style="margin-right: 10px;"><a href="#">#{{ $tag->name }} </a></span><br>
                                @endforeach
                            </td>
                            <td>{{ $post->category ? $post->category->name : '' }}</td>
                            <td style="width: 300px;">{!! Str::limit($post->body, 400) !!}</td>
                            <td class="text-center">{{ $post->comments_count}}</td>
                            <td>{{ date('d-m-y H:i', strtotime($post->created_at)) }}</td>
                            <td>{{ date('d-m-y H:i', strtotime($post->updated_at)) }}</td>
                            <td class="text-center">
                                <a href="post/{{$post->id}}" class="btn">
                                    <i class="fa fa-eye"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="post/{{$post->id}}/edit" class="btn">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <form action="post/{{$post->id}}" method="post" onsubmit="return confirm('Veux-tu vraiment delete le post belle gosse ?')" class="d-inline">
                                    {{ csrf_field() }}
                                    @method('DELETE')
                                    <button class="btn" type="submit">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->


        <div class="card">
        <div class="card-header">
            <h2>Les brouillons</h2>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
                <table class="table table-bordered">

                    <thead>
                        <tr>
                            <th>Img</th>
                            <th>Title</th>
                            <th>Tag</th>
                            <th>Categorie</th>
                            <th>Contenu</th>
                            <th>Cree le</th>
                            <th>Modifier le</th>
                            <th class="text-center">Voir</th>
                            <th class="text-center">Modif</th>
                            <th class="text-center">Suppr</th>
                        </tr>
                    </thead>

                    <tbody>
                    @foreach($postsDraft as $post)
                        <tr>
                            <td style="width: 150px;">
                                <img src="{!! $post->main_img !!}" alt="{{ $post->alt_main_img }}" style="width: 100%;">
                            </td>
                            <td style="width: 150px;">{{ $post->title }}</td>
                            <td>
                                @foreach($post->tags as $tag)
                                    <span style="margin-right: 10px;"><a href="#">#{{ $tag->name }} </a></span><br>
                                @endforeach
                            </td>
                            <td>{{ $post->category ? $post->category->name : '' }}</td>
                            <td style="width: 300px;">{!! Str::limit($post->body, 400) !!}</td>
                            <td>{{ date('d-m-y H:i', strtotime($post->created_at)) }}</td>
                            <td>{{ date('d-m-y H:i', strtotime($post->updated_at)) }}</td>
                            <td class="text-center">
                                <a href="post/{{$post->id}}" class="btn">
                                    <i class="fa fa-eye"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="post/{{$post->id}}/edit" class="btn">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <form action="post/{{$post->id}}" method="post" onsubmit="return confirm('Veux-tu vraiment delete le post belle gosse ?')" class="d-inline">
                                    {{ csrf_field() }}
                                    @method('DELETE')
                                    <button class="btn" type="submit">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>

                </table>
            </div>
        <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </div>

    <script>
        $(document).ready(function() {
            $('#example1').DataTable({
                "responsive": true,
                "autoWidth": false,
                "order": [[ 5, "desc" ]]
            });
        } );
    </script>
@endsection

resources/views/admin/posts/create.blade.php
@extends('admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Écrire un article') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="/admin/post" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="title">Titre de l'article</label>
                            <input type="text" name="title" class="form-control" minlength="30" maxlength="60">
                        </div>

                        <div class="form-group">
                            <label for="chapo">Chapeau de l'article</label>
                            <input type="text" name="chapo" class="form-control" maxlength="200">
                        </div>

                        <div class="form-group">
                            <label for="meta_title">Meta title</label>
                            <input type="text" name="meta_title" class="form-control" disabled>
                        </div>

                        <div class="form-group">
                            <label for="meta_desc">Meta description</label>
                            <input type="text" name="meta_desc" class="form-control" maxlength="200">
                        </div>

                        <div class="form-group">
                            <label for="location">Lieu de l'article</label>
                            <input type="text" name="location" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="tag">Tag</label>
                            <select class="form-control js-example-tags" multiple="multiple" name="tagsTet[]">
                                @foreach($tags as $tag);
                                    <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="category">Catégories</label>
                            <select name="category" id="category" class="form-control">
                                <option value="">--Choisir une catégorie--</option>
                                @foreach($categories as $key => $category);
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="image">Image de présentation</label>
                                    <input type="file" name="file" id="file" class="form-control-file">
                                </div>
                                <div class="col-md-4">
                                    <label for="alt_main_img">Texte alt</label>
                                    <input type="text" name="alt_main_img" class="form-control">
                                </div>
                                <div class="col-md-4">
                                    <label for="name_img">Nom de l'image</label>
                                    <input type="text" name="name_img" class="form-control" disabled>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="h3" for="">Contenu de l'article</label>
                            <textarea name="body" id="" cols="30" rows="10" class="textarea"></textarea>
                        </div>

                        <input type="submit" class="btn btn-green" name="publish" value="Publier">
                        <input type="submit" class="btn btn-green" name="draft" value="Enregistrer comme brouillon">

                        {{--<button type="submit" class="btn btn-green">Enregistrer</button>
                        <button type="subm">Enregistrer comme brouillon</button>--}}
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Modifier l\'article') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="/admin/post/{{$post->id}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="title">Titre de l'article</label>
                            <input type="text" name="title" class="form-control" minlength="30" maxlength="60" value="{{$post->title}}">
                        </div>

                        <div class="form-group">
                            <label for="title">Chapeau de l'article</label>
                            <input type="text" name="chapo" class="form-control" maxlength="200" value="{{$post->chapo}}">
                        </div>

                        <div class="form-group">
                            <label for="meta_title">Meta title</label>
                            <input type="text" name="meta_title" class="form-control" disabled>
                        </div>

                        <div class="form-group">
                            <label for="meta_desc">Meta description</label>
                            <input type="text" name="meta_desc" class="form-control" maxlength="200" value="{{$post->meta_desc}}">
                        </div>

                        <div class="form-group">
                            <label for="location">Lieu de l'article</label>
                            <input type="text" name="location" class="form-control" value="{{$post->location}}">
                        </div>

                        <div class="form-group">
                            <label for="tag">Tag</label>
                            <select class="form-control js-example-tags" multiple="multiple" name="tagsTet[]">
                                @foreach($tags as $tag)
                                    @foreach($post->tags as $actual_tag)
                                        @if($actual_tag->id === $tag->id)
                                            <option value="{{ $tag->id }}" selected="selected">{{ $tag->name }}</option>
                                        @else
                                            <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                        @endif
                                    @endforeach
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="category">Catégories</label>
                            <select name="category" id="category" class="form-control">
                                <option value="">--Choisir une catégorie--</option>
                                @foreach($categories as $key => $category);
                                    @if($category->id === $post->category_id)
                                        <option value="{{ $category->id }}" selected="selected">{{ $category->name }}</option>
                                    @else
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="image">Image de presentation</label>
                                    <input type="file" name="file" id="file" class="form-control-file" value="{{ $post->main_img }}">
                                </div>
                                <div class="col-md-4">
                                    <label for="alt_img">Texte alt</label>
                                    <input type="text" name="alt_main_img" class="form-control" value="{{$post->alt_main_img}}">
                                </div>
                                <div class="col-md-4">
                                    <label for="name_img">Nom de l'image</label>
                                    <input type="text" name="name_img" class="form-control" disabled>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="h3" for="body">Contenu de l'article</label>
                            <textarea name="body" id="" cols="30" rows="10" class="textarea">{!! $post->body !!}</textarea>
                        </div>

                        <input type="submit" class="btn btn-green" name="publish" value="Publier">
                        <input type="submit" class="btn btn-green" name="draft" value="Enregistrer comme brouillon">

                        {{--<button type="submit" class="btn btn-green">Mettre à jour</button>--}}
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection